language: java
jdk:
  - oraclejdk8
deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: asgardian-walkure-core
  if: branch = release/liv
before_install:
  - chmod +x mvnw
# safelist
branches:
  only:
    - release/liv
    - dev